--PRODUCT
--하우스 번호, 하우스명, 후기 개수, 타입, 생성일
CREATE TABLE TB_HOUSE(
    HOUSE_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(4000),
    RATE_COUNT VARCHAR2(400),
    TYPE VARCHAR2(20),
    CREATE_DATE DATE
    );
CREATE SEQUENCE SEQ_HOUSE;

--FILE
--파일번호, 내가 딸린 하우스번호, 원본명, 수정명
CREATE TABLE TB_FILE(
    FILE_NO NUMBER PRIMARY KEY,
    REF_HOUSE_NO NUMBER REFERENCES TB_HOUSE,
    ORIGIN_NAME VARCHAR2(500),
    CHANGE_NAME VARCHAR2(500)
);
CREATE SEQUENCE SEQ_FILE;

SELECT * FROM TB_HOUSE;
SELECT * FROM TB_file;

SELECT
        HOUSE_NO,
        TITLE,
        RATE_COUNT,
        TYPE,
        CREATE_DATE,
        ORIGIN_NAME,
        CHANGE_NAME
  FROM
        TB_HOUSE
  JOIN
        TB_FILE ON (HOUSE_NO = REF_HOUSE_NO)
 WHERE
        TYPE = 'pools'
 ORDER
    BY
        CREATE_DATE DESC;
