create user C##BOOT IDENTIFIED BY BOOT;
GRANT CONNECT, RESOURCE TO C##BOOT;

GRANT CREATE ANY TABLE TO C##BOOT;
GRANT CONNECT, RESOURCE, DBA TO C##BOOT;
ALTER USER C##BOOT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;